import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/footer'
import Hero from './components/Hero/Hero'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harry Potter',
  description: 'Generated by Harry Potter',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
    >
         <body className={inter.className}>{children}
      
      <br /><br />
      <Footer/>
      </body>
    </html>
  )
}
